### ISSUE TITLE
Want to improve Alert UI

### ISSUE THREAD

**Issue by devp299** [TheOpenInnovator/ChromaVerse#8] opened 2024-10-11 07:22 UTC
I see and go through your website. When I click on any color generated it shows very basic alert. I want to make Alert very good looking and user experiencing.

**Comment by devp299** [comment] 2024-10-11 07:22
Please assign this issue under hacktoberfest

**Comment by TheOpenInnovator** [comment] 2024-10-11 11:15
@devp299 sure the issue is assigned to you. You can start working on it.

**Closed** 2024-10-13 03:20 UTC
Labels: enhancement, hacktoberfest, HacktoberFest2024, hacktoberfest-accepted
